baseURL = "https://mollyillustration.com/"
languageCode = "en-us"
title = "Molly Beres Illustration & Design"
copyright = "© 2018 Molly Beres"
theme = "genesee"

[params]
  facebook = "mollyillustrationofficial"
  instagram = "molly_illustration"
  linkedin = "molly-beres-899a52157"
  author = "Molly Beres"

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 10

[[menu.main]]
  name = "Illustration & Design"
  url = "/work"
  weight = 20

[[menu.main]]
  name = "Shop"
  url = "https://www.etsy.com/shop/MollyIllustration"
  weight = 30

[[menu.main]]
  name = "Blog"
  url = "/posts"
  weight = 40

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 50
